import crypto from "crypto"; type Sql={query:<T=any>(q:string,p?:any[])=>Promise<T[]>}; let sql:Sql|null=null,initialized=false;
async function getSql(){if(initialized)return sql;initialized=true;const url=(process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.NEON_DATABASE_URL||"").trim();if(!url)return null;try{const m=await import("@neondatabase/serverless");sql=m.neon(url) as unknown as Sql;return sql;}catch(e){console.warn("[COMPANY] DB unavailable:",(e as Error).message);return null;}}
const id=(p:string)=>p+"-"+Date.now()+"-"+crypto.randomBytes(4).toString("hex");
export async function listCompanies(){const db=await getSql();return db?db.query("SELECT * FROM companies ORDER BY created_at DESC LIMIT 100"):null;}
export async function createCompany(x:any){const db=await getSql();if(!db)return null;const rows=await db.query("INSERT INTO companies(id,name,description,mission,monthly_budget,governance) VALUES($1,$2,$3,$4,$5,$6::jsonb) RETURNING *",[id("company"),String(x.name||"Unnamed Company"),String(x.description||""),String(x.mission||""),Number(x.monthlyBudget||0),JSON.stringify(x.governance||{})]);return rows[0];}
export async function listMissions(companyId?:string){const db=await getSql();if(!db)return null;return companyId?db.query("SELECT * FROM missions WHERE company_id=$1 ORDER BY created_at DESC LIMIT 100",[companyId]):db.query("SELECT * FROM missions ORDER BY created_at DESC LIMIT 100");}
export async function createMission(x:any){const db=await getSql();if(!db)return null;const rows=await db.query("INSERT INTO missions(id,company_id,name,objective,status,success_criteria,budget,metadata) VALUES($1,$2,$3,$4,'queued',$5,$6,$7::jsonb) RETURNING *",[id("mission"),String(x.companyId),String(x.name||"Mission"),String(x.objective||""),String(x.successCriteria||""),Number(x.budget||0),JSON.stringify(x.metadata||{})]);return rows[0];}
export async function getMission(id:string){const db=await getSql();if(!db)return null;const rows=await db.query("SELECT * FROM missions WHERE id=$1",[id]);return rows[0]||null;}
export async function startMission(id:string){const db=await getSql();if(!db)return null;const rows=await db.query("UPDATE missions SET status='running',started_at=COALESCE(started_at,now()),updated_at=now() WHERE id=$1 RETURNING *",[id]);return rows[0]||null;}
