import { app } from "../dist/server.cjs";

/**
 * Vercel serverless entrypoint.
 *
 * Import the bundled CommonJS server artifact generated by `npm run build`.
 * Importing `../server` resolves to a directory in the deployed Node.js 24
 * runtime and fails with ERR_UNSUPPORTED_DIR_IMPORT before any API route runs.
 * The build command creates dist/server.cjs before Vercel packages this entry.
 */
export default app;
